jira:
  url: https://url.of.jira/
  statuses:
  - name: Backlog
    display: ğŸ”µ
  - name: Selected for Development
    display: ğŸŒ‘
  - name: Ready for Development
    display: ğŸŒ˜
  - name: In Progress
    display: ğŸŒ—
  - name: In Review
    display: ğŸŒ–
  - name: Awaiting Merge
    display: ğŸŒ•
  - name: Awaiting Demo
    display: ğŸ”†
  - name: Done
    display: âœ…
  - name: Closed
    display: C
  - name: Duplicate
    display: D
  issuetypes:
  - name: Story
    display: ğŸ“–
  - name: Bug
    display: ğŸ
  - name: Task
    display: ğŸ”§
